package univ.savemother.models;


import java.util.Date;

/**
 * DoctorApointment generated by hbm2java
 */
public class DoctorApointment implements java.io.Serializable {

	private Integer id;
	private Doctor doctor;
	private Woman woman;
	private Date apointmentDate;

	public DoctorApointment() {
	}

	public DoctorApointment(Doctor doctor, Woman woman, Date apointmentDate) {
		this.doctor = doctor;
		this.woman = woman;
		this.apointmentDate = apointmentDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Woman getWoman() {
		return this.woman;
	}

	public void setWoman(Woman woman) {
		this.woman = woman;
	}

	public Date getApointmentDate() {
		return this.apointmentDate;
	}

	public void setApointmentDate(Date apointmentDate) {
		this.apointmentDate = apointmentDate;
	}

}
