package univ.savemother.models;



import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor implements java.io.Serializable {

	private Integer id;
	private String doctorName;
	private String specialization;
	private String mobile;
	private String experience;
	private String gender;
	private String hospitalName;
	private String hospitalNumber;
	private String city;
	private Set doctorApointments = new HashSet(0);

	public Doctor() {
	}

	public Doctor(String doctorName, String specialization, String mobile, String experience, String gender,
			String hospitalName, String hospitalNumber, String city) {
		this.doctorName = doctorName;
		this.specialization = specialization;
		this.mobile = mobile;
		this.experience = experience;
		this.gender = gender;
		this.hospitalName = hospitalName;
		this.hospitalNumber = hospitalNumber;
		this.city = city;
	}

	public Doctor(String doctorName, String specialization, String mobile, String experience, String gender,
			String hospitalName, String hospitalNumber, String city, Set doctorApointments) {
		this.doctorName = doctorName;
		this.specialization = specialization;
		this.mobile = mobile;
		this.experience = experience;
		this.gender = gender;
		this.hospitalName = hospitalName;
		this.hospitalNumber = hospitalNumber;
		this.city = city;
		this.doctorApointments = doctorApointments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDoctorName() {
		return this.doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getHospitalName() {
		return this.hospitalName;
	}

	public void setHospitalName(String hospitalName) {
		this.hospitalName = hospitalName;
	}

	public String getHospitalNumber() {
		return this.hospitalNumber;
	}

	public void setHospitalNumber(String hospitalNumber) {
		this.hospitalNumber = hospitalNumber;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Set getDoctorApointments() {
		return this.doctorApointments;
	}

	public void setDoctorApointments(Set doctorApointments) {
		this.doctorApointments = doctorApointments;
	}

}
