package univ.savemother.models;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Woman generated by hbm2java
 */
public class Woman implements java.io.Serializable {

	private Integer id;
	private String fullname;
	private String division;
	private String district;
	private String opazila;
	private String union;
	private String mobile;
	private Date lmpDate;
	private Date dueDate;
	private Integer cycledays;
	private Float height;
	private Float weight;
	private Integer ovulationdays;
	private Set doctorApointments = new HashSet(0);

	public Woman() {
	}

	public Woman(String fullname, String division, String district, String opazila, String union, String mobile) {
		this.fullname = fullname;
		this.division = division;
		this.district = district;
		this.opazila = opazila;
		this.union = union;
		this.mobile = mobile;
	}

	public Woman(String fullname, String division, String district, String opazila, String union, String mobile,
			Date lmpDate, Date dueDate, Integer cycledays, Float height, Float weight, Integer ovulationdays,
			Set doctorApointments) {
		this.fullname = fullname;
		this.division = division;
		this.district = district;
		this.opazila = opazila;
		this.union = union;
		this.mobile = mobile;
		this.lmpDate = lmpDate;
		this.dueDate = dueDate;
		this.cycledays = cycledays;
		this.height = height;
		this.weight = weight;
		this.ovulationdays = ovulationdays;
		this.doctorApointments = doctorApointments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getOpazila() {
		return this.opazila;
	}

	public void setOpazila(String opazila) {
		this.opazila = opazila;
	}

	public String getUnion() {
		return this.union;
	}

	public void setUnion(String union) {
		this.union = union;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Date getLmpDate() {
		return this.lmpDate;
	}

	public void setLmpDate(Date lmpDate) {
		this.lmpDate = lmpDate;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Integer getCycledays() {
		return this.cycledays;
	}

	public void setCycledays(Integer cycledays) {
		this.cycledays = cycledays;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getWeight() {
		return this.weight;
	}

	public void setWeight(Float weight) {
		this.weight = weight;
	}

	public Integer getOvulationdays() {
		return this.ovulationdays;
	}

	public void setOvulationdays(Integer ovulationdays) {
		this.ovulationdays = ovulationdays;
	}

	public Set getDoctorApointments() {
		return this.doctorApointments;
	}

	public void setDoctorApointments(Set doctorApointments) {
		this.doctorApointments = doctorApointments;
	}

}
